
POST http://localhost:8080/users
Content-Type: application/json 

{  
    "firstName": "Francis",
    "lastName": "Francis",
    "password":"password",
    "email":"fr@gmail.com"
   
}

GET http://localhost:8080/getAllUsers
Content-Type: application/json


GET http://localhost:8080/users/2

//PUT http://localhost:8080/users?firstname="John"?lastname="Cooks"

PUT  http://localhost:8080/updateUser/2
Content-Type: application/json 

{
    "firstName": "Miya",
    "lastName": "Uriel",
    "password":"newpassword",
    "email":"aure@gmail.com"
    
   
}

DELETE   http://localhost:8080/deleteUser/1
Content-Type: application/json



PUT  http://localhost:8080/deactivateUser/1
Content-Type: application/json 

{
    "active": "false"
}




