
POST http://localhost:8080/users
Content-Type: application/json 

{  
    "firstName": "aaaaa",
    "lastName": "gggggg",
    "password":"password",
    "email":"ak@gmail.com"
   
}

GET http://localhost:8080/getAllUsers
Content-Type: application/json


GET http://localhost:8080/users/1

//PUT http://localhost:8080/users?firstname="John"?lastname="Cooks"

PUT  http://localhost:8080/updateUser/1
Content-Type: application/json 

{
    "firstName": "Miya",
    "lastName": "Uriel",
    "password":"newpassword",
    "email":"aure@gmail.com"
    
   
}

DELETE   http://localhost:8080/deleteUser/1
Content-Type: application/json



