
POST http://localhost:8080/users
Content-Type: application/json 

{  
    "firstName": "Aurelie",
    "lastName": "Aurelie",
    "password":"password",
    "email":"aure@gmail.com"
   
}

GET http://localhost:8080/getAllUsers
Content-Type: application/json


GET http://localhost:8080/users/2
Content-Type: application/json

//PUT http://localhost:8080/users?firstname="John"?lastname="Cooks"

PUT  http://localhost:8080/updateUser/1
Content-Type: application/json 

{
    "firstName": "Miya",
    "lastName": "Uriel",
    "password":"newpassword",
    "email":"aure@gmail.com"
    
   
}



PUT  http://localhost:8080/deactivateUser/2
Content-Type: application/json 

{

    "active": "true"

}



PUT  http://localhost:8080/desableUser/2
Content-Type: application/json 

{

    "active": "false"
    
}





